services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    ports:
      - "9091:9091"
    environment:
      - TZ=Europe/Paris
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      # On bascule sur ta nouvelle racine propre
      - /docker/services/authelia:/config